---
- hosts: all
  become: yes
  gather_facts: no

  vars:
    db_name: aiueo
    db_user: aiueo
    db_password: aiueo

  tasks:
    - name: Install required packages
      dnf:
        name:
          - wget
          - httpd
          - php
          - php-fpm
          - php-json
          - php-mysqlnd
          - mariadb105-server
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB to start
      wait_for:
        port: 3306
        state: started
        delay: 5
        timeout: 30

    - name: Ensure pip is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present
      become: true

    - name: Install Python MySQL library via pip
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3
      become: true

    - name: Change MariaDB root authentication method to password
      become: true
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        plugin: mysql_native_password
        state: present
        check_implicit_admin: yes
        login_unix_socket: "{{ item }}"
      loop:
        - /var/lib/mysql/mysql.sock
        - /run/mysqld/mysqld.sock
      ignore_errors: true
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Create WordPress database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user and grant privileges
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
  
    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz
        mode: '0644'

    - name: Create /var/www/html/wordpress directory
      file:
        path: /var/www/html/wordpress
        state: directory
        mode: '0755'
      become: true

    - name: Extract WordPress directly into /var/www/html/wordpress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/wordpress/
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /var/www/html/wordpress/index.php
        owner: apache
        group: apache
        mode: '0755'

    - name: Update wp-config.php for database settings
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^define\s*\(\s*'DB_NAME',", line: "define( 'DB_NAME', '{{ db_name }}' );' }
        - { regexp: '^define\s*\(\s*'DB_USER',", line: "define( 'DB_USER', '{{ db_user }}' );' }
        - { regexp: '^define\s*\(\s*'DB_PASSWORD',", line: "define( 'DB_PASSWORD', '{{ db_password }}' );' }

    - name: Set correct permissions
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes
