---
- hosts: all
  become: yes
  gather_facts: no

  vars:
    db_name: aiueo
    db_user: aiueo
    db_password: aiueo

  tasks:
    - name: Install required packages
      dnf:
        name:
          - wget
          - httpd
          - php
          - php-fpm
          - php-json
          - php-mysqlnd
          - mariadb105-server
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

    - name: Wait for MariaDB to start
      wait_for:
        port: 3306
        state: started
        delay: 5

    - name: Install Python MySQL library
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present
      become: true

    - name: Create WordPress database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root

    - name: Create MySQL user and grant privileges
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz
        mode: '0644'

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Copy wp-config.php from sample
      command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
      args:
        creates: /var/www/html/wordpress/wp-config.php

    - name: Update wp-config.php for database settings
      lineinfile:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "define\\('DB_NAME',", line: "define('DB_NAME', '{{ db_name }}');" }
        - { regexp: "define\\('DB_USER',", line: "define('DB_USER', '{{ db_user }}');" }
        - { regexp: "define\\('DB_PASSWORD',", line: "define('DB_PASSWORD', '{{ db_password }}');" }

    - name: Copy WordPress to /var/www/html
      command: cp -r /var/www/html/wordpress/* /var/www/html/
      args:
        creates: /var/www/html/index.php

    - name: Create /var/www/html/blog directory
      file:
        path: /var/www/html/blog
        state: directory
        mode: '0755'

    - name: Copy WordPress to /var/www/html/blog
      command: cp -r /var/www/html/wordpress/* /var/www/html/blog/
      args:
        creates: /var/www/html/blog/index.php

    - name: Set correct permissions
      file:
        path: /var/www/html/
        owner: apache
        group: apache
        recurse: yes
